name: Update Forecasts
on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:        # Allows you to run it manually to test

jobs:
  run-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: {python-version: '3.9'}
      - name: Install dependencies
        run: pip install pandas matplotlib seaborn scikit-learn xgboost
      - name: Run script
        run: python working_model.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update forecast results" || exit 0
          git push
